plugins:
  discourse_global_filter_enabled:
    default: true
    client: true
  global_filters:
    type: tag_list
    client: true
    default: ""
  replace_global_filter_with_children:
    default: false
    client: true
