plugins:
  discourse_global_filter_enabled:
    default: true
    client: true
  global_filters:
    type: tag_list
    client: true
    default: ""
  display_subcategories_for_tag_intersection:
    default: false
    client: true
  replace_global_filter_with_children:
    default: false
    client: true
